### ISSUE TITLE
Working w/ Opnsense

### ISSUE THREAD

**Issue by shermdog** [aus/pfatt#15]
I've gotten IPv4 working fine w/ OPNsense 18.7.  The netgraph module is already included so the only difference is commenting out the `pfSense_ngctl_attach` commands and putting the script in  `/usr/local/etc/rc.syshook.d/early/`

Haven't been able to get IPv6 working though.  I'll spend some more time with it and see what I can do.  PR to hopefully follow.

**Comment by shermdog** [comment]
IPv6 looks okay now.  Going to give this some time to make sure everything is stable and will submit PR

**Comment by shermdog** [comment]
Have uncovered an issue with netflow.  The init script hits the following:

`root@firewall:/usr/local/etc/rc.d # /usr/sbin/ngctl mkpeer ngeth0: netflow lower iface9
ngctl: send msg: Protocol family not supported`

I'm not well versed in netgraph, but perhaps netflow isn't support on `eiface` types.  May be able to work around by getting the underlying physical interface available in the opnsense config, but will take some playing around.

**Comment by aus** [comment]
Interesting. It seems the `EPFNOSUPPORT` error will trigger on `ng_eiface` nodes (which creates the virtual Ethernet interface from netgraph) but not `ng_ether` nodes (which allows netgraph to interface with existing Ethernet devices). You might be right about `ng_eiface` not being supported with `ng_netflow` somehow. I'm not sure why though. This happens on pfSense too, but pfSense uses softflowd for netflow which doesn't use netgraph.

`ng_netflow` should work fine against the LAN interface, since `pfatt` doesn't create any netgraph hooks into the LAN interface.

But unfortunately, it won't be as simple as swapping `ngeth0` for `$ONT_IF` since `$ONT_IF:lower` is already connected to the one2many node.  But you should be able to drop in on the `many2` hook. So in the case of the [ngctl command](https://github.com/opnsense/core/blob/master/src/etc/rc.d/netflow#L87L94), you might try something like this instead:

```shell
/usr/sbin/ngctl -f-  <<-SEQ
       mkpeer o2m: netflow many2 iface$ifIndex
       name o2m:many2 netflow_$interface
       connect $interface: netflow_$interface: upper	out$ifIndex
       mkpeer netflow_$interface: ksocket export$nfversion inet/dgram/udp
       msg netflow_$interface: setconfig {iface=$ifIndex conf=$conf}
       msg netflow_$interface:export$nfversion connect inet/$netflow_int_destination
SEQ
```

That's a complete shot in the dark and untested, but give it a go.

**Comment by shermdog** [comment]
Thus far not working.  Need to dig deeper, but not optimistic.  Not the end of the world for me, but hoping to keep everything fully functional if possible.

**Comment by aus** [comment]
Well, I see one possible problem: I forgot to update the o2m config and enable the many2 link. Maybe try this:

```shell
/usr/sbin/ngctl -f-  <<-SEQ
       mkpeer o2m: netflow many2 iface$ifIndex
       name o2m:many2 netflow_$interface
       msg o2m: setconfig "{ xmitAlg=2 failAlg=1 enabledLinks=[ 1 1 1 ] }"
       connect $interface: netflow_$interface: upper	out$ifIndex
       mkpeer netflow_$interface: ksocket export$nfversion inet/dgram/udp
       msg netflow_$interface: setconfig {iface=$ifIndex conf=$conf}
       msg netflow_$interface:export$nfversion connect inet/$netflow_int_destination
SEQ
```

**Comment by shermdog** [comment]
That doesn't want to work as part of the init script
```
ngctl: send msg: Invalid argument
ngctl: line 3: error in file
```
But does seem to accept it afterwards :man_shrugging: 
```
root@OPNsense:~ # /usr/sbin/ngctl msg o2m: setconfig "{ xmitAlg=2 failAlg=1 enabledLinks=[ 1 1 1 ] }"
root@OPNsense:~ # echo $?
0
```

However still unable to attach the upper, which I believe is the issue at large based on the graph from the LAN side.

`connect $interface: netflow_$interface: upper	out$ifIndex`
ngctl: send msg: Protocol family not supported

Omitting that line builds everything out, but not capturing any data.


![image](https://user-images.githubusercontent.com/3383063/50874425-956e6c80-1389-11e9-8296-b28a69183031.png)
(graph visual included from test VM, but same result with physical box)

**Comment by darkfiberiru** [comment]
Quick Comments/questions on your visual graph. Trying to understand this as I want this running too 

You have vlan1 listed not vlan0 

What are your 4 interface you have em0-3 in your graph with the whole disconnected right side(s) looking not relevant.  Should only need the ont and router gateway ports + ngeth0

**Comment by shermdog** [comment]
@darkfiberiru here is the graph from my production system.  The above graph was just for working out some netflow bits.

![image](https://user-images.githubusercontent.com/3383063/52242498-74237200-289c-11e9-9034-6a67305a17d8.png)

I have 2 distinct LAN interfaces in my setup

* igb0 ONT
* igb1 RG
* igb2 LAN2
* igb3 LAN1

**Comment by cspencer49519** [comment]
I have this working under opnsense as well, but I seem to be encountering issues with ipv6 too. While I can reach ipv6 addresses, I do not get an ipv6 gateway address from att, and I'm unsure how to get the gateway address myself. Would like to see if there are any differences in my setup versus yours.

**Comment by lrosenman** [comment]
I'm working great with IPv6.  

do note that the default gateway will be a link-local address to the ngeth0 interface:
Internet6:
Destination                       Gateway                       Flags     Netif Expire
default                           fe80::2d0:f6ff:fe2d:7f88%ngeth0 UG     ngeth0
::1                               link#6                        UH          lo0
2600:1700:210:b180::/64           link#1                        U           em0
2600:1700:210:b180:242:43ff:feac:29c link#1                     UHS         lo0
fe80::%em0/64                     link#1                        U           em0
fe80::242:43ff:feac:29c%em0       link#1                        UHS         lo0
fe80::%em2/64                     link#3                        U           em2
fe80::242:43ff:feac:29e%em2       link#3                        UHS         lo0
fe80::%em3/64                     link#4                        U           em3
fe80::242:43ff:feac:29f%em3       link#4                        UHS         lo0
fe80::%lo0/64                     link#6                        U           lo0
fe80::1%lo0                       link#6                        UHS         lo0
fe80::%ngeth0/64                  link#9                        U        ngeth0
fe80::e2b7:aff:fea1:d441%ngeth0   link#9                        UHS         lo0
root@OPNsense:~ # ifconfig ngeth0
ngeth0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=28<VLAN_MTU,JUMBO_MTU>
	ether e0:b7:0a:a1:d4:41
	inet6 fe80::e2b7:aff:fea1:d441%ngeth0 prefixlen 64 scopeid 0x9
	inet 76.250.255.117 netmask 0xfffffc00 broadcast 76.250.255.255
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
root@OPNsense:~ 

root@OPNsense:~ # ping6 ipv6.google.com
PING6(56=40+8+8 bytes) 2600:1700:210:b180:242:43ff:feac:29c --> 2607:f8b0:4000:816::200e
16 bytes from 2607:f8b0:4000:816::200e, icmp_seq=0 hlim=55 time=7.721 ms
16 bytes from 2607:f8b0:4000:816::200e, icmp_seq=1 hlim=55 time=7.611 ms
^C
--- ipv6.l.google.com ping6 statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 7.611/7.666/7.721/0.055 ms
root@OPNsense:~ #20 

does your LAN interface get IPv6?

Do also note that ngeth0 does *NOT* get a public (2600::) address.
(that surprised me, but it works, so who cares).

**Comment by lrosenman** [comment]
@aus any chance of adding an "OPNSense" configure variable to skip the pfsense_add_interfaces for when you are on OPNSense? (Works great with those lines commented out).

**Comment by aus** [comment]
I will take a pull request for that. Don’t have an opnsense environment
handy to test.

**Comment by lrosenman** [comment]
I'm not sure how to change a git clone to a fork, but this works:
diff --git a/bin/pfatt.sh b/bin/pfatt.sh
index 31167df..b35402a 100755
--- a/bin/pfatt.sh
+++ b/bin/pfatt.sh
@@ -4,6 +4,7 @@ set -e
 ONT_IF='em0'
 RG_IF='em1'
 RG_ETHER_ADDR='xx:xx:xx:xx:xx:xx'
+OPNSENSE='no'
 LOG=/var/log/pfatt.log

 getTimestamp(){
@@ -16,15 +17,18 @@ getTimestamp(){
     echo "$(getTimestamp)        ONT_IF: $ONT_IF"
     echo "$(getTimestamp)         RG_IF: $RG_IF"
     echo "$(getTimestamp) RG_ETHER_ADDR: $RG_ETHER_ADDR"
+    echo "$(getTimestamp)      OPNSENSE: $OPNSENSE"

     echo -n "$(getTimestamp) loading netgraph kernel modules... "
     /sbin/kldload -nq ng_etf
     echo "OK!"

-    echo -n "$(getTimestamp) attaching interfaces to ng_ether... "
-    /usr/local/bin/php -r "pfSense_ngctl_attach('.', '$ONT_IF');"
-    /usr/local/bin/php -r "pfSense_ngctl_attach('.', '$RG_IF');"
-    echo "OK!"
+    if [ ${OPNSENSE} != 'yes' ]; then
+        echo -n "$(getTimestamp) attaching interfaces to ng_ether... "
+        /usr/local/bin/php -r "pfSense_ngctl_attach('.', '$ONT_IF');"
+        /usr/local/bin/php -r "pfSense_ngctl_attach('.', '$RG_IF');"
+        echo "OK!"
+    fi

     echo "$(getTimestamp) building netgraph nodes..."

[lrosenman:~/GIT/pfatt/bin] add_opnsense_config ±

**Comment by audioeptesicus** [comment]
This is impressive. I just had AT&T fiber installed today and didn't realize that I would need to do something like this just so that I could access things remotely like I could with Cincinnati Bell's Fioptics. I too and running OPNsense and am anxious to get this working. Does anyone have a completely process to get this working on OPNsense? I'm only utilizing IPv4 at the moment. Also, I'm running OPNsense 19.1.4 on FreeBSD 11.2. Hopefully everything will translate well from the OP's 18.7.

**Comment by lrosenman** [comment]
@audioeptesicus just follow the instructions he did (I'm on 19.1) and make the change I did above, and set OPNSENSE to yes. 

It works GREAT!

**Comment by lrosenman** [comment]
and do *NOT* worry about the IPv6 duid stuff, I didn't do it, and got my IPv6 prefix.

**Comment by lrosenman** [comment]
and you *CAN* use IPv6 Prefix id 0 with OpnSense.  It does NOT put an IPv6 address on ngeth0.

**Comment by lrosenman** [comment]
https://github.com/aus/pfatt/pull/21

**Comment by lrosenman** [comment]
[https://www.lerctr.org/~ler/ng.png]

My graph of the netgraph stuff.

**Comment by audioeptesicus** [comment]
Thanks @lrosenman!

So what I did to get mine working (to organize it better for those of us who may not be as versed as you all :) )... Hopefully this sticks if power gets disconnected from the ONT.

pfatt.sh:
```
#!/bin/sh
set -e

ONT_IF='igb0'   # NIC -> ONT / Outside
RG_IF='igb3'   # NIC -> Residential Gateway's ONT port
RG_ETHER_ADDR='xx:xx:xx:xx:xx:xx'   # MAC address of Residential Gateway
OPNSENSE='yes'
LOG=/var/log/pfatt.log

getTimestamp(){
    echo `date "+%Y-%m-%d %H:%M:%S :: [pfatt.sh] ::"`
}

{
    echo "$(getTimestamp) pfSense + AT&T U-verse Residential Gateway for true bridge mode"
    echo "$(getTimestamp) Configuration: "
    echo "$(getTimestamp)        ONT_IF: $ONT_IF"
    echo "$(getTimestamp)         RG_IF: $RG_IF"
    echo "$(getTimestamp) RG_ETHER_ADDR: $RG_ETHER_ADDR"
	echo "$(getTimestamp)      OPNSENSE: $OPNSENSE"

    echo -n "$(getTimestamp) loading netgraph kernel modules... "
    /sbin/kldload -nq ng_etf
    echo "OK!"

    #echo -n "$(getTimestamp) attaching interfaces to ng_ether... "
    #/usr/local/bin/php -r "pfSense_ngctl_attach('.', '$ONT_IF');" 
    #/usr/local/bin/php -r "pfSense_ngctl_attach('.', '$RG_IF');"
    #echo "OK!"
	
    if [ ${OPNSENSE} != 'yes' ]; then
        echo -n "$(getTimestamp) attaching interfaces to ng_ether... "
        /usr/local/bin/php -r "pfSense_ngctl_attach('.', '$ONT_IF');"
        /usr/local/bin/php -r "pfSense_ngctl_attach('.', '$RG_IF');"
        echo "OK!"
    fi

    echo "$(getTimestamp) building netgraph nodes..."

    echo -n "$(getTimestamp)   creating ng_one2many... "
    /usr/sbin/ngctl mkpeer $ONT_IF: one2many lower one
    /usr/sbin/ngctl name $ONT_IF:lower o2m
    echo "OK!"

    echo -n "$(getTimestamp)   creating vlan node and interface... "
    /usr/sbin/ngctl mkpeer o2m: vlan many0 downstream
    /usr/sbin/ngctl name o2m:many0 vlan0
    /usr/sbin/ngctl mkpeer vlan0: eiface vlan0 ether

    /usr/sbin/ngctl msg vlan0: 'addfilter { vlan=0 hook="vlan0" }'
    /usr/sbin/ngctl msg ngeth0: set $RG_ETHER_ADDR
    echo "OK!"

    echo -n "$(getTimestamp)   defining etf for $ONT_IF (ONT)... "
    /usr/sbin/ngctl mkpeer o2m: etf many1 downstream
    /usr/sbin/ngctl name o2m:many1 waneapfilter
    /usr/sbin/ngctl connect waneapfilter: $ONT_IF: nomatch upper
    echo "OK!"

    echo -n "$(getTimestamp)   defining etf for $RG_IF (RG)... "
    /usr/sbin/ngctl mkpeer $RG_IF: etf lower downstream
    /usr/sbin/ngctl name $RG_IF:lower laneapfilter
    /usr/sbin/ngctl connect laneapfilter: $RG_IF: nomatch upper
    echo "OK!"

    echo -n "$(getTimestamp)   bridging etf for $ONT_IF <-> $RG_IF... "
    /usr/sbin/ngctl connect waneapfilter: laneapfilter: eapout eapout
    echo "OK!"

    echo -n "$(getTimestamp)   defining filters for EAP traffic... "
    /usr/sbin/ngctl msg waneapfilter: 'setfilter { matchhook="eapout" ethertype=0x888e }'
    /usr/sbin/ngctl msg laneapfilter: 'setfilter { matchhook="eapout" ethertype=0x888e }'
    echo "OK!"

    echo -n "$(getTimestamp)   enabling one2many links... "
    /usr/sbin/ngctl msg o2m: setconfig "{ xmitAlg=2 failAlg=1 enabledLinks=[ 1 1 ] }"
    echo "OK!"

    echo -n "$(getTimestamp)   removing waneapfilter:nomatch hook... "
    /usr/sbin/ngctl rmhook waneapfilter: nomatch
    echo "OK!"

    echo -n "$(getTimestamp) enabling $RG_IF interface... "
    /sbin/ifconfig $RG_IF up
    echo "OK!"

    echo -n "$(getTimestamp) enabling $ONT_IF interface... "
    /sbin/ifconfig $ONT_IF up
    echo "OK!"

    echo -n "$(getTimestamp) enabling promiscuous mode on $RG_IF... "
    /sbin/ifconfig $RG_IF promisc
    echo "OK!"

    echo -n "$(getTimestamp) enabling promiscuous mode on $ONT_IF... "
    /sbin/ifconfig $ONT_IF promisc
    echo "OK!"

    echo "$(getTimestamp) ngeth0 should now be available to configure as your pfSense WAN"
    echo "$(getTimestamp) done!"
} >> $LOG
```

1. Save `pfatt.sh` to `/usr/local/etc/rc.syshook.d/early/`

2. `chmod +x /usr/local/etc/rc.syshook.d/early/pfatt.sh`

3. Edit `/conf/config.xml` to include `<earlyshellcmd>/usr/local/etc/rc.syshook.d/early/pfatt.sh</earlyshellcmd>` above `</system>`.

4. Connect cables to appropriate interfaces. For me... ONT/WAN to `igb0`, LAN to `igb1`, and BGW210-700's ONT port to `igb3`.

5. Reboot OPNsense firewall.

6. After reboot, change WAN interface to the new `ngeth0` interface

7. Check logs (/var/log/pfatt.log) to ensure everything is successful.
```
2019-04-03 15:42:36 :: [pfatt.sh] :: pfSense + AT&T U-verse Residential Gateway for true bridge mode
2019-04-03 15:42:36 :: [pfatt.sh] :: Configuration:
2019-04-03 15:42:36 :: [pfatt.sh] ::        ONT_IF: igb0
2019-04-03 15:42:36 :: [pfatt.sh] ::         RG_IF: igb3
2019-04-03 15:42:36 :: [pfatt.sh] :: RG_ETHER_ADDR: #####################
2019-04-03 15:42:36 :: [pfatt.sh] ::      OPNSENSE: yes
2019-04-03 15:42:36 :: [pfatt.sh] :: loading netgraph kernel modules... OK!
2019-04-03 15:42:36 :: [pfatt.sh] :: building netgraph nodes...
2019-04-03 15:42:36 :: [pfatt.sh] ::   creating ng_one2many... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   creating vlan node and interface... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   defining etf for igb0 (ONT)... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   defining etf for igb3 (RG)... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   bridging etf for igb0 <-> igb3... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   defining filters for EAP traffic... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   enabling one2many links... OK!
2019-04-03 15:42:36 :: [pfatt.sh] ::   removing waneapfilter:nomatch hook... OK!
2019-04-03 15:42:36 :: [pfatt.sh] :: enabling igb3 interface... OK!
2019-04-03 15:42:36 :: [pfatt.sh] :: enabling igb0 interface... OK!
2019-04-03 15:42:36 :: [pfatt.sh] :: enabling promiscuous mode on igb3... OK!
2019-04-03 15:42:36 :: [pfatt.sh] :: enabling promiscuous mode on igb0... OK!
2019-04-03 15:42:36 :: [pfatt.sh] :: ngeth0 should now be available to configure as your pfSense WAN
2019-04-03 15:42:36 :: [pfatt.sh] :: done!
```

Hooray! Hopefully everything will work well after an outage (knock on wood). Gotta ensure all of my self-hosted services are accessible remotely after an outage occurs.

**Comment by lrosenman** [comment]
I didn't even have to modify config.xml, it apparently just runs the scripts in that directory (and to make sure it runs at the end, I named it 99-pfatt.sh.

Works like a dream.

**Comment by lrosenman** [comment]
to test mine, I just pulled the plug on my ONT (It's in my guest bedroom on a UPS)....

Oh, and my damn cats occasionally hit the UPS' power button.
