### ISSUE TITLE
PFSense in Failover

### ISSUE THREAD

**Issue by zombielinux** [aus/pfatt#20]
Currently I have PFSense virtualized on one of three proxmox hypervisors in their recommended HA setup. 

I've got the output of the Pace 5268AC connected into one port on my switch (Brocade VDX6710), it gets a VLAN tag, and sent on its way to my PFSense box. 

How can I properly set this up such that I can eliminate the Pace? It seems this solution depends on multiple dedicated physical NICs.

**Comment by aus** [comment]
I don't have a lot of experience with running Proxmox in HA, so take this for whats it worth. I ran my pfsense as VM at one point, but not in a HA VM environment. My implementation consisted of utilizing PCI passthrough for the physical NIC, which wouldn't work if the VM was failed over to another host.

The alternative to pci passthrough is using the `group_fwd_mask` option in Linux. That may workout better in HA, but its another layer of complexity. 

I believe you can also run pfSense in HA (ie multiple pfSense VMs), but I don't have any experience with that. Not sure that's a feasible option.

Your best bet is probably going to be extracting valid 802.1X keys and eliminating your Router Gateway completely. Take a look at my supplicant PR #19 for details on that.

**Comment by zombielinux** [comment]
@aus Interesting. So you managed to extract the 802.1X keys from your ATT Gateway? Would you mind detailing how you did that? I've got one cracked open at the moment and am trying to find the time to get into the root console.

**Comment by aus** [comment]
Take a look at devicelocksmith.com and the posts on DSLreports for instructions.
