### ISSUE TITLE
Small correction on commands

### ISSUE THREAD

**Issue by RailRanger** [aus/pfatt#23]
I noticed under these instructions

Copy bin/pfatt-5268AC to /usr/local/etc/rc.d/

Copy bin/pfatt-5268AC.sh to /root/bin/:

```
scp bin/pfatt-5268AC root@pfsense:/usr/local/etc/rc.d/pfatt-5268AC.sh
scp bin/pfatt-5268AC.sh root@pfsense:/root/bin/
ssh root@pfsense chmod +x /usr/local/etc/rc.d/pfatt-5268AC.sh /root/bin/pfatt-5268AC.sh
```

I believe this should be:
`ssh root@pfsense chmod +x /usr/local/etc/rc.d/pfatt-5268AC /root/bin/pfatt-5268AC.sh`

There was a .sh at the end of the first file, it should be removed.

Thanks for all the hard work by the way, it works great.

**Comment by romracer** [comment]
This is not wrong I believe.  The command (which I copied from your comment):

`scp bin/pfatt-5268AC root@pfsense:/usr/local/etc/rc.d/pfatt-5268AC.sh`

The file will end up as `/usr/local/etc/rc.d/pfatt-5268AC.sh`.  Therefore, the chmod would need to be:

`ssh root@pfsense chmod +x /usr/local/etc/rc.d/pfatt-5268AC.sh`

as it is in the docs.  Now, if your first command ended at `rc.d`, the file would end up as `pfatt-5268AC` and your correction would be warranted, but that's not what the docs say.

**Comment by Berzerker** [comment]
They're not wrong, but they *are* a bit confusing. I think the names of the files should be a little more clear so people don't `scp` the wrong file.

The `rc` init file should be something like `5268AC-init.sh` while the workaround script should be `5268AC-pingfix.sh` or something along those lines. Obviously my names aren't the best, but something more clear would certainly help.

**Comment by aus** [comment]
Feel free to open a PR for improving, but closing this since its not an issue.
