### ISSUE TITLE
IPv6 is not routable

### ISSUE THREAD

**Issue by RomanHargrave** [aus/pfatt#27]
While I have been assigned an IPv6 prefix, and RA or DHCP clients can receive them, pfSense is having issues routing that traffic.

This appears to have something to do with the WAN IPv6 gateway being a local (fe80:) address. I'm not entirely certain that this is normal (even for AT&T).

Has anyone been able to mitigate this issue?

**Comment by RomanHargrave** [comment]
From what I can tell, the `fe80::` default gateway is to be expected, and it is alive.
I'm still baffled by the fact that ATT's network is seemingly an IPv6 black hole - everything looks fine but v6 traffic is not being routed.

**Comment by lrosenman** [comment]
I'm using ATT Fiber with OPNSense and routing IPv6 just fine.  
Are you sure you are Prefix-Delegating IP's to your LAN?

**Comment by johndong** [comment]
What I’ve noticed is that the firewall itself is assigned a strange unrouteable IPv6 address that only allows getting to their DNSv6 servers but not the general internet. All the other prefixes get working subnets though. On PFSense this starts affecting things like being able to reach the updates/packages server.

**Comment by lrosenman** [comment]
That does *NOT* happen with OPNSense.  The NGEth0 doesn't get a routable IPv6, but does get the fe80:: link-local address.

ngeth0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=28<VLAN_MTU,JUMBO_MTU>
	ether e0:b7:0a:a1:d4:41
	inet6 fe80::e2b7:aff:fea1:d441%ngeth0 prefixlen 64 scopeid 0xb
	inet 76.250.255.117 netmask 0xfffffc00 broadcast 76.250.255.255
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active

root@home-fw:~ # ping6 ipv6.google.com
PING6(56=40+8+8 bytes) 2600:1700:210:b180:2e0:67ff:fe05:a09c --> 2607:f8b0:4000:811::200e
16 bytes from 2607:f8b0:4000:811::200e, icmp_seq=0 hlim=54 time=10.301 ms
16 bytes from 2607:f8b0:4000:811::200e, icmp_seq=1 hlim=54 time=10.392 ms
^C
--- ipv6.l.google.com ping6 statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 10.301/10.346/10.392/0.046 ms
root@home-fw:~ #

so this *MAYBE* a PFSense issue.

**Comment by RomanHargrave** [comment]
I could certainly try OPNsense.

@Irosenman can you run a traceroute from a computer on one of the the delegated prefixes, as well as from your router? What is your default gateway (post-\*sense). Also, yes, I using a delegate prefix for my LAN, and my devices are getting 2006:: addresses (or something like that)

**Comment by lrosenman** [comment]
From my iMac (it may resolve differently due to my VPN DNS settings using DNS at our AWS EndPoint in VA vs here in Austin):
[I] ➜ traceroute6 ipv6.google.com
traceroute6 to ipv6.l.google.com (2607:f8b0:4004:810::200e) from 2600:1700:210:b180:5102:55cd:bef5:4de, 64 hops max, 12 byte packets
 1  2600:1700:210:b180:2e0:67ff:fe05:a09c  0.396 ms  0.419 ms  0.321 ms
 2  2001:506:6000:100:76:253:217:11  1.013 ms  1.240 ms  0.931 ms
 3  2001:506:6000:100:69:235:125:190  1.591 ms  1.539 ms  1.531 ms
 4  2001:1890:ff:ffff:12:122:118:103  10.668 ms  10.900 ms  10.711 ms
 5  2001:1890:c00:2c30::115f:f63f  10.491 ms
    2001:1890:c00:2c2f::113e:1ed4  10.614 ms
    2001:1890:c01:a602::1167:9fb2  10.927 ms
 6  2607:f8b0:8274::1  10.845 ms
    2607:f8b0:80f1::1  10.628 ms
    2607:f8b0:8209::1  10.763 ms
 7  2001:4860::c:4000:d8f6  14.130 ms  11.144 ms
    2001:4860:0:1::2784  11.464 ms
 8  2001:4860::c:4001:557b  44.808 ms
    2001:4860:0:e02::11  11.389 ms
    2001:4860:0:e03::12  11.266 ms
 9  2001:4860::c:0:d108  45.175 ms
    2001:4860::c:4000:d8f6  19.613 ms  11.141 ms
10  2001:4860::c:4000:d387  44.105 ms
    2001:4860::c:4000:e361  27.383 ms  27.563 ms
11  2001:4860::9:4001:14e4  44.253 ms  43.851 ms
    2001:4860::c:4001:5890  44.431 ms
12  2001:4860:0:1098::1  44.517 ms
    2001:4860::c:4000:d387  43.725 ms  44.059 ms
13  2001:4860::9:4001:14e4  44.187 ms
    2001:4860::1:4000:c8a3  45.430 ms
    iad23s63-in-x0e.1e100.net  43.686 ms

~ took 3s
[I] ➜


From OPNSense (my router essentially) using my normal Austin Based DNS.
root@home-fw:~ # traceroute6 ipv6.google.com
traceroute6 to ipv6.l.google.com (2607:f8b0:4000:803::200e) from 2600:1700:210:b180:2e0:67ff:fe05:a09c, 64 hops max, 20 byte packets
 1  2001:506:6000:100:76:253:217:11  0.807 ms  0.803 ms  0.692 ms
 2  2001:506:6000:100:69:235:125:190  1.327 ms  1.266 ms  1.381 ms
 3  2001:1890:ff:ffff:12:122:118:103  10.594 ms  10.485 ms  10.565 ms
 4  2001:1890:c01:a602::1167:9fb2  10.383 ms
    2001:1890:c00:2c2f::113e:1ed4  10.313 ms  10.184 ms
 5  2607:f8b0:8210::1  10.432 ms *
    2001:4860:0:e02::1  11.654 ms
 6  2001:4860:0:1::427  10.467 ms
    2001:4860:0:1::2b7a  11.146 ms
    2001:4860:0:1::427  10.652 ms
 7  2001:4860:0:1::501  10.310 ms
    2001:4860:0:11e4::3  10.802 ms
    dfw25s13-in-x0e.1e100.net  10.338 ms
root@home-fw:~ #

**Comment by RomanHargrave** [comment]
It is interesting that your OPNsense installation is using 2600:: addresses on its interface. When I request an address from their network I get a 2001:506:: at the router, and a delegated 2600:: block which is then used by the LAN interface.

I think that this may have something to do with the way that OPNsense is assigning addresses to interfaces versus, in my case PFsense. ATT's network should be very similar for you if you are in Austin - I'm in DFW.

**Comment by lrosenman** [comment]
I forgot the routing table:

OPNSense:
```
root@home-fw:~ # netstat -6rn
Routing tables

Internet6:
Destination                       Gateway                       Flags     Netif Expire
default                           fe80::2d0:f6ff:fe2d:7f88%ngeth0 UG     ngeth0
::1                               link#8                        UH          lo0
2600:1700:210:b180::/64           link#1                        U           em0
2600:1700:210:b180:2e0:67ff:fe05:a09c link#1                    UHS         lo0
fe80::%em0/64                     link#1                        U           em0
fe80::2e0:67ff:fe05:a09c%em0      link#1                        UHS         lo0
fe80::%em4/64                     link#5                        U           em4
fe80::2e0:67ff:fe05:a0a0%em4      link#5                        UHS         lo0
fe80::%em5/64                     link#6                        U           em5
fe80::2e0:67ff:fe05:a0a1%em5      link#6                        UHS         lo0
fe80::%lo0/64                     link#8                        U           lo0
fe80::1%lo0                       link#8                        UHS         lo0
fe80::%ngeth0/64                  link#11                       U        ngeth0
fe80::e2b7:aff:fea1:d441%ngeth0   link#11                       UHS         lo0
root@home-fw:~ #
``` 

iMac:
```
[I] ➜ netstat -f inet6 -r -n
Routing tables

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::2e0:67ff:fe05:a09c%en0    UGc             en0
default                                 fe80::%utun0                    UGcI          utun0
::1                                     ::1                             UHL             lo0
2600:1700:210:b180::/64                 link#6                          UC              en0
2600:1700:210:b180::4e                  78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:2e0:67ff:fe05:a09c   0:e0:67:5:a0:9c                 UHLWI           en0
2600:1700:210:b180:80d:aab9:10b3:c1ee   78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:24c4:6232:cc2e:5c65  78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:4c24:fd26:d30c:ae75  78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:5102:55cd:bef5:4de   78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:618b:e19b:4ff6:4b3e  78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:a6ba:dbff:fe29:6695  a4:ba:db:29:66:95               UHLWI           en0
2600:1700:210:b180:d457:6284:3e37:9a92  78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:d80a:bc9a:d088:18e1  78:7b:8a:bc:4b:6b               UHL             lo0
2600:1700:210:b180:f906:7404:d938:2ce3  78:7b:8a:bc:4b:6b               UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#6                          UCI             en0
fe80::2e0:67ff:fe05:a09c%en0            0:e0:67:5:a0:9c                 UHLWIir         en0
fe80::10ed:12ec:a404:c11%en0            78:7b:8a:bc:4b:6b               UHLI            lo0
fe80::%utun0/64                         fe80::51ad:c382:111b:12dd%utun0 UcI           utun0
fe80::51ad:c382:111b:12dd%utun0         link#13                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#6                          UmCI            en0
ff01::%en1/32                           link#7                          UmCI            en1
ff01::%awdl0/32                         link#11                         UmCI          awdl0
ff01::%utun0/32                         fe80::51ad:c382:111b:12dd%utun0 UmCI          utun0
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#6                          UmCI            en0
ff02::%en1/32                           link#7                          UmCI            en1
ff02::%awdl0/32                         link#11                         UmCI          awdl0
ff02::%utun0/32                         fe80::51ad:c382:111b:12dd%utun0 UmCI          utun0

~
[I] ➜
```

**Comment by RomanHargrave** [comment]
The gateway is definitely correct then. As for addressing on the WAN interface - do you have `Request only an IPv6 prefix` (or the OPNSense equivalent) checked?

**Comment by lrosenman** [comment]
No option for that.

**Comment by RomanHargrave** [comment]
I think that's what it may be doing. Though I wonder why the network is routing traffic for you. What does your DHCP client configuration look like, if you don't mind?

**Comment by lrosenman** [comment]
<img width="1722" alt="Screen Shot 2019-06-30 at 5 28 59 PM" src="https://user-images.githubusercontent.com/2868525/60402991-d8e9ac80-9b5c-11e9-8e0d-a3c4126411f4.png">
<img width="1695" alt="Screen Shot 2019-06-30 at 5 30 06 PM" src="https://user-images.githubusercontent.com/2868525/60402995-dab37000-9b5c-11e9-888c-3db116511ece.png">
<img width="1712" alt="Screen Shot 2019-06-30 at 5 30 50 PM" src="https://user-images.githubusercontent.com/2868525/60402997-dd15ca00-9b5c-11e9-969d-f8447c51463c.png">
<img width="1714" alt="Screen Shot 2019-06-30 at 5 31 44 PM" src="https://user-images.githubusercontent.com/2868525/60403005-f3bc2100-9b5c-11e9-8b64-f43687ba0789.png">

**Comment by lrosenman** [comment]
Basically, it's NOT assigning a Public IPv6 to the WAN interface (which is fine, it doesn't need one), and delegating the 0 PD to the LAN.  

IIRC PFsense reservices PD 0 for itself.

**Comment by RomanHargrave** [comment]
I think that the PD 0 issue may be it. I'll have to verify - though that can be worked around with a custom dhcp client configuration which has not proven fruitful thus far...

**Comment by lrosenman** [comment]
I think some of it is due to Link-Local for the WAN interface (the fe80:: prefix is Link-Local), unlike IPv4, IPv6 does NOT require Public IPs on the routing interfaces, just a link-local address for the next hop.

**Comment by lrosenman** [comment]
N.B.: My WAN interface (ngeth0) does *NOT* have a public/routable IPv6, just a Link-Local address.  And when I do a ping6/traceroute6 it uses the LAN interface Public/routable IPv6.

**Comment by lrosenman** [comment]
Also, note what setting OPNSENSE="yes" sets inside the shell script that sets up the netgraph stuff.  PFSense is definitely "Different" in what all it does IPv6 wise vs OPNSense.

**Comment by RomanHargrave** [comment]
> IPv6 does NOT require Public IPs on the routing interfaces

I had gathered as much. I'm trying to get a lease again so that I can see if I can troubleshoot routing more. Knowing what OPNsense does differently would certainly help to diagnose.

**Comment by lrosenman** [comment]
I've not looked in detail at PFSense in a few years due to a philosophical problem with the current PFSense maintainers.  I've been an active OPNSense user since that time (except for when I was using a Ubiquiti USG, which I ditched a few months ago as underpowered for what I wanted to do). 

I'm not sure what all PFSense exactly is doing, but with OPNSENSE I needed to skip 2 calls into PFSense for the pfatt stuff to work on OPNSense.  (I'm the guy that added the OPNSENSE= Configuration Variable here).

**Comment by RomanHargrave** [comment]
Tried with near identical settings. This is certainly something that - if I had more detail - I could probably fix with PFsense; however, I think I'll save myself the trouble and try OPNsense. I'll report back. I guess at this point we'll know if this is a regional issue.

**Comment by lrosenman** [comment]
I've heard similar grief with ATT/pfSense.   I just don't have the desire to troubleshoot it. 

This works, and the OPNSense folks are friendly and mostly responsive.

**Comment by RomanHargrave** [comment]
@lrosenman Interesting. Fresh OPNsense install - no configuration imported. Same interface settings as yours. I get the delegation, but IPv6 traffic is not routed. Sniffing traffic to the ONT shows IPv6 traffic outgoing, but nothing the other way around.

**Comment by lrosenman** [comment]
I assume you've set up aus/pfatt so that your ONT is authorized.  Sometimes it takes a few minutes for the PD to work.  I also assume that your LAN interface now has a IPv6 public address.

I have my LAN set to TRACK the ngeth0 interface, and that is what is set as my WAN address.

**Comment by lrosenman** [comment]
and do you have FireWall rules to allow the IPv6 stuff out/in?

**Comment by lrosenman** [comment]
<img width="1769" alt="Screen Shot 2019-06-30 at 7 36 09 PM" src="https://user-images.githubusercontent.com/2868525/60404414-5833ac00-9b6e-11e9-89d0-398afa94c4db.png">

**Comment by RomanHargrave** [comment]
Yes, that's all set up. Enable IPv6 is checked, ngeth0 is the WAN interface and LAN is tracking it.

**Comment by lrosenman** [comment]
what does your ipv6 route table look like on the FW?

**Comment by RomanHargrave** [comment]
```
Routing tables

Internet6:
Destination                       Gateway                       Flags     Netif Expire
default                           fe80::8626:2bff:fe8b:c971%ngeth0 UG    ngeth0
::1                               link#7                        UH          lo0
2600:1700:50f:110::/64            link#1                        U        cxgbe0
2600:1700:50f:110:207:43ff:fe10:3320 link#1                     UHS         lo0
fe80::%cxgbe0/64                  link#1                        U        cxgbe0
fe80::207:43ff:fe10:3320%cxgbe0   link#1                        UHS         lo0
fe80::%cxgbe3/64                  link#4                        U        cxgbe3
fe80::207:43ff:fe10:3338%cxgbe3   link#4                        UHS         lo0
fe80::%re0/64                     link#5                        U           re0
fe80::e23f:49ff:fe44:aeef%re0     link#5                        UHS         lo0
fe80::%lo0/64                     link#7                        U           lo0
fe80::1%lo0                       link#7                        UHS         lo0
fe80::%ngeth0/64                  link#10                       U        ngeth0
fe80::1293:97ff:fe4d:9cb1%ngeth0  link#10                       UHS         lo0
```

**Comment by lrosenman** [comment]
<img width="1305" alt="Screen Shot 2019-06-30 at 7 41 13 PM" src="https://user-images.githubusercontent.com/2868525/60404489-2111ca80-9b6f-11e9-9f7d-afa5e541308b.png">
<img width="1725" alt="Screen Shot 2019-06-30 at 7 41 37 PM" src="https://user-images.githubusercontent.com/2868525/60404492-240cbb00-9b6f-11e9-9af4-cbd10cc08ac8.png">

**Comment by lrosenman** [comment]
Are you running the RA daemon?  (see settings above

**Comment by RomanHargrave** [comment]
Yep, caught that right before your comment. Clients are addressed; however, no routing still - not that RA would have much to do with that.

**Comment by lrosenman** [comment]
ping ipv6.google.com fails, right?

what does the ipv6 routing look like on a lan client?
what does the interface look like ipv6 wise on the lan client?

**Comment by RomanHargrave** [comment]
Pinging fails from the FW and Clients.

```
PING6(56=40+8+8 bytes) 2600:1700:50f:110:207:43ff:fe10:3320 --> 2607:f8b0:4000:816::200e
^C
--- ipv6.l.google.com ping6 statistics ---
6 packets transmitted, 0 packets received, 100.0% packet loss
```

Client routing:

```
OK/0 : ~❯❯❯ ip -6 route show dev eth0                                                                                                                                                                                                                                                           Sun 30 Jun 2019 07:46:04 PM CDT
2600:1700:50f:110::50 proto kernel metric 100 pref medium
2600:1700:50f:110::/64 proto ra metric 100 pref medium
fe80::/64 proto kernel metric 100 pref medium
default via fe80::207:43ff:fe10:3320 proto ra metric 100 pref medium
```

Client interface
```
OK/0 : ~❯❯❯ ip -6 addr show dev eth0                                                                                                                                                                                                                                                            Sun 30 Jun 2019 07:46:14 PM CDT
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2600:1700:50f:110::50/128 scope global dynamic noprefixroute 
       valid_lft 6964sec preferred_lft 4264sec
    inet6 2600:1700:50f:110:51aa:7a38:99:4ecf/64 scope global dynamic noprefixroute 
       valid_lft 86211sec preferred_lft 14211sec
    inet6 fe80::9606:2d50:fbc8:9c10/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Comment by RomanHargrave** [comment]
I can confirm as well that the firewall is permitting outgoing IPv6 traffic from LAN clients - I've seen it in the live log.

**Comment by lrosenman** [comment]
weird.  IIRC when I first did this it took a little, and then poof it just worked.  Can you give it an hour and then check it?

Once it starts working it's fine.  

(this was a few months ago for me).

If you want send me a phone number and/or email address to ler at FreeBSD.org and we can do this live instead of back and forth over GitHub comments.

**Comment by RomanHargrave** [comment]
I'll give it an hour. I'll go ahead and shoot an email. Though I have to wonder if this is an ATT problem.

**Comment by lrosenman** [comment]
I doubt it's a long-term ATT problem.  I do recall it taking a bit when the MAC addresses, etc changed. 
Let's see what happens after a bit, and make sure all the settings, etc are good.  I do know it's working fine here. 

So, <something> is subtlely different with your IPv6 setup vs. mine.

**Comment by RomanHargrave** [comment]
> So, is subtlely different with your IPv6 setup vs. mine.

I would hope.

**Comment by lrosenman** [comment]
feel free to send that email sooner rather than later.  I also work from home so I'm generally around here.

**Comment by RomanHargrave** [comment]
Already sent.

**Comment by RomanHargrave** [comment]
As I had suspected, me and @lrosenman have come to the conclusion that this is an ATT-internal routing problem.
