### ISSUE TITLE
Updating/Upgrading pfSense/OPNsense

### ISSUE THREAD

**Issue by pvols1979** [aus/pfatt#28]
Based on the kernel patch used for pfSense, I would assume that future updates/upgrades would break the netgraph configuration and require stepping through the setup again.  Is there a plan to work around that?  Also, since OPNsense offers netgraph in the kernel, does that mean that an update/upgrade would not require any fixes?  I am rebuilding my firewall and this would make me lean in the direction of OPNsense.

**Comment by lrosenman** [comment]
No it doesn't.  I've upgraded from OPNSense 19.1 to 19.7 and my netgraph stuff was still there.  

I'm not sure on PFSense.

**Comment by pvols1979** [comment]
Interesting.  Thank you for the quick reply.  This is truly a set it and forget it config for bypassing on OPNsense.

**Comment by lrosenman** [comment]
yes.
