### ISSUE TITLE
Bypass ONT?

### ISSUE THREAD

**Issue by jasonsansone** [aus/pfatt#33]
Has anyone attempted (or ideally achieved) a bypass of the AT&T ONT? I am successfully bypassing the Residential Gateway, but I was curious about taking the fiber directly in to an SFP or SFP+ NIC. Latency should be superior by avoiding the media conversion to copper. The same NIC could then connect to a switch via fiber on a different port.

**Comment by lrosenman** [comment]
I doubt that will work, as it needs the authentication.

**Comment by lrosenman** [comment]
I also think ATT would consider the ONT their DMARC.

**Comment by jasonsansone** [comment]
Is the ONT providing any authentication or just media conversion? The device has a MAC, but that could be spoofed just like the RG.

**Comment by lrosenman** [comment]
I'm not up on all the technicalities, but If it was me, I wouldn't worry about it, and just use the ONT. 

As I said, I suspect ATT considers the ONT the DMARC and NOT available to be replaced by Customer Equipment.

**Comment by jasonsansone** [comment]
Thank you. Figured I would explore the idea, but I’ll heed your advice and leave it alone.
