### ISSUE TITLE
ng_eth not found when doing a kldstat -v

### ISSUE THREAD

**Issue by jku209** [aus/pfatt#37]
I'm have an issue with ng_eth module is not found when I kldstat -v. I'm not really sure how to troubleshoot this. I have the ng_eth loaded because I get run ngctl command okay.

**Comment by Powderwt** [comment]
As having just successfully completed all this I can try and help..

When you are in the CLI of the actually pfsense box, as in at a keyboard and monitor connected to it, can you navigate to the /boot/kernel/ directory and then run late -al ? I had a weird instance where mine was an ungodly large file size somehow and had to redownload the file from GitHub and it fixed my issues. 

Also after typing that, you should see the permissions to the very left of ng_etf, it should show I believe -r-xr-xr-x for having 555 permissions. I assigned mine 755 not thinking it would matter too much but just to clarify.

**Comment by jku209** [comment]
I see that the ng_eft.ko file is 12.80k and with the permissions of 755 as well.

**Comment by Powderwt** [comment]
When I redownloaded it a second time and uploaded it using the file upload
tool under command prompt tab in pfsense, mine was just over 9k.

Not sure if it matters, but I would change the permission to 555 as the
guide suggests just to try and minimize any issues.

**Comment by jku209** [comment]
did a clean install and that solve the my issue.
