### ISSUE TITLE
pfatt.sh

### ISSUE THREAD

**Issue by rda1990** [aus/pfatt#38]
I need help figuring out what I am doing wrong I cant get /root/bin/pfatt.sh to be found by boot up. 

the message I keep getting on boot is sh: /root/bin/pfatt.sh: not found

I have the line in the config file as
		<earlyshellcmd>/root/bin/pfatt.sh</earlyshellcmd>
	</system>

The file is in /root/bin/

**Comment by Powderwt** [comment]
Could you clarify what you mean, can't get it to be found by bootup? 

When you are using the CLI directly connected at your pfsense, (keyboard and mouse plugged into it), can you navigate to the /root/bin/ directory and verify that PFATT.sh is indeed there?

**Comment by rda1990** [comment]
yes it is there and the permissions are
Total 5
5 -rwr-xr-x 1 root wheel 3405 nov 8 20:48 pfatt.sh

**Comment by Powderwt** [comment]
Ok, did you create the dir in /root/ ? As in /root/bin/ doesn't exist until you create it, then you need to make sure to move the pfatt.sh to the dir /root/bin/pfatt.sh

**Comment by rda1990** [comment]
yes, the file is in /root/bin/pfatt.sh

**Comment by Powderwt** [comment]
Okay, now that's clarified, you say it is at boot up? Where are you seeing:

>  I keep getting on boot is sh: /root/bin/pfatt.sh: not found

**Comment by rda1990** [comment]
![Region Capture](https://user-images.githubusercontent.com/19717561/68564436-a01ce680-041e-11ea-84c9-b38b7998a5e3.jpg)
Yes that is right I am getting the error on boot up.

**Comment by rda1990** [comment]
![Region Capture](https://user-images.githubusercontent.com/19717561/68564551-e96d3600-041e-11ea-9f40-37d737cfcc52.jpg)

**Comment by Powderwt** [comment]
Could you do me a favor and from your pfsense machine:

`cd /root/bin/ ls -al`

And take a pic and post it?

**Comment by rda1990** [comment]
![Region Capture](https://user-images.githubusercontent.com/19717561/68564903-ea529780-041f-11ea-9fa7-fedf1fa9f3ac.jpg)

**Comment by Powderwt** [comment]
Also, if you can access the webgui of pfsense from another machine, go-to: 
Diagnostics> Edit File 
Then click browse and navigate to
`/Var/log/pfatt.log`
And post what you find there

**Comment by rda1990** [comment]
I do not have the pf box connected to the network yet I am just trying to setup first, also in the /var/log/ there is no pfatt.log

**Comment by Powderwt** [comment]
OHHHH!! ONE MORE THING! (Sorry caps, just remembered this part) 

Your `/conf/config.xml` file, could you open that and screenshot the section of:
```
<system>.......
    Bunch of stuff here....
</system>

```

**Comment by Powderwt** [comment]
> I do not have the pf box connected to the network yet I am just trying to setup first, also in the /var/log/ there is no pfatt.log

Ok, so I have a feeling you may have pasted the `<earlyshellcmd>` in the wrong spot possibly.

**Comment by rda1990** [comment]
<system>
		<optimization>normal</optimization>
		<hostname>pfSense</hostname>
		<domain></domain>
		<dnsserver>1.1.1.1</dnsserver>
		<dnsserver>1.0.0.1</dnsserver>
		<dnsallowoverride>on</dnsallowoverride>
		<group>
			<name>all</name>
			<description><![CDATA[All Users]]></description>
			<scope>system</scope>
			<gid>1998</gid>
		</group>
		<group>
			<name>admins</name>
			<description><![CDATA[System Administrators]]></description>
			<scope>system</scope>
			<gid>1999</gid>
			<member>0</member>
			<priv>page-all</priv>
		</group>
		<user>
			<name>admin</name>
			<descr><![CDATA[System Administrator]]></descr>
			<scope>system</scope>
			<groupname>admins</groupname>
			<bcrypt-hash></bcrypt-hash>
			<uid>0</uid>
			<priv>user-shell-access</priv>
			<expires></expires>
			<dashboardcolumns>2</dashboardcolumns>
			<authorizedkeys></authorizedkeys>
			<ipsecpsk></ipsecpsk>
			<webguicss>pfSense.css</webguicss>
		</user>
		<nextuid>2000</nextuid>
		<nextgid>2000</nextgid>
		<timeservers>0.pfsense.pool.ntp.org</timeservers>
		<webgui>
			<protocol>https</protocol>
			<loginautocomplete></loginautocomplete>
			<ssl-certref>5dc677f02f29a</ssl-certref>
			<dashboardcolumns>2</dashboardcolumns>
			<port></port>
			<max_procs>2</max_procs>
		</webgui>
		<disablenatreflection>yes</disablenatreflection>
		<disablesegmentationoffloading></disablesegmentationoffloading>
		<disablelargereceiveoffloading></disablelargereceiveoffloading>
		<ipv6allow></ipv6allow>
		<maximumtableentries>400000</maximumtableentries>
		<powerd_ac_mode>hadp</powerd_ac_mode>
		<powerd_battery_mode>hadp</powerd_battery_mode>
		<powerd_normal_mode>hadp</powerd_normal_mode>
		<bogons>
			<interval>monthly</interval>
		</bogons>
		<already_run_config_upgrade></already_run_config_upgrade>
		<timezone>America/New_York</timezone>
		<ssh>
			<enable>enabled</enable>
			<sshdkeyonly>both</sshdkeyonly>
		</ssh>
		<serialspeed>115200</serialspeed>
		<primaryconsole>serial</primaryconsole>
		<sshguard_threshold></sshguard_threshold>
		<sshguard_blocktime></sshguard_blocktime>
		<sshguard_detection_time></sshguard_detection_time>
		<sshguard_whitelist></sshguard_whitelist>
		<earlyshellcmd>/root/bin/pfatt.sh</earlyshellcmd>
	</system>

**Comment by rda1990** [comment]
[New1.txt](https://github.com/aus/pfatt/files/3829908/New1.txt)

**Comment by Powderwt** [comment]
is `</system>` not directly under `<system>` like in the new1.txt file you just attached in your config file?

Should be like this:
[New1.txt](https://github.com/aus/pfatt/files/3829960/New1.txt)

**Comment by rda1990** [comment]
yes the one you sent is the way it looks.

**Comment by Powderwt** [comment]
> yes the one you sent is the way it looks.

Okay, so unfortunately I'm not the best source of expertise on this, but I feel like you've done everything right. 
My only suggestion could be to get pfsense setup with this pfatt workaround. Get it running to where you can login to the webgui and THEN try doing this pfatt workaround. I'm not sure it matters or not, but most things I've read, it sounds like everyone's had it set up and running already before trying this. Worth a shot at least!

**Comment by rda1990** [comment]
I can login when I am in the office, i have a cable hooked up from the box to my computer. I should be able to setup the vlan and bridge with out taking down my network. I was doing over the supermicro interface.

**Comment by rda1990** [comment]
Could not get script to run just setup up the code by hand.
