### ISSUE TITLE
Can't compile package directly on pfsense

### ISSUE THREAD

**Issue by MonkWho** [aus/pfatt#4]
We can't compile netgraph directly on pfsense since "make" is not installed. Developers have chosen not to allow compiling on the firewall for "security and capacity reasons" - https://www.netgate.com/docs/pfsense/development/compiling-software-on-the-firewall.html

Might want to add that to readme so people don't get stuck on that step. I'm going to use my secondary virtual test pfsense to compile the package.

**Comment by aus** [comment]
I did note that as a "trusted FreeBSD 11.1 machine" but I will clarify. Thanks.
