### ISSUE TITLE
Pace 5268AC sends periodic EAP-Logoff after valid EAP authentication

### ISSUE THREAD

**Issue by aus** [aus/pfatt#5]
With pfatt, the ARRIS NVG589 and BGW210-700 will maintain EAP authentication and active broadband service after receiving an `EAP-Success` from the gateway. pfatt will bridge any EAP traffic to handle any re-authentication, like after a reboot/outage, disconnect or if the gateway requests an `EAP-Request,Identify` (which may never actually happen under normal circumstances).

The Pace 5268AC works the same way. However, the 5268AC will send an `EAPOL-Logoff` periodically, even after completing EAP authentication and receiving `EAP-Success`. This causes the gateway to respond with an `EAP-Failure`, which causes your broadband service to stop periodically until re-authentication is completed.

I can speculate that this is a difference in how the 5268AC firmware attempts to re-establish broadband service while detecting a non-good broadband state. Knowing that the 5268AC has successfully completed EAP authentication but not received a DHCP lease for the public IP, the Broadband service light will blink a non-good state (off, blinking green, red). This behavior is by pfatt's design, since we request and assign the public IP from pfSense. However, the 5268AC likely sees the lack of a DHCP lease and public IP as a broken broadband state. It probably then tries to cleanup with an `EAP-Logoff` in order to restart the broadband service establishment process (EAP, DHCP).

Since pfatt will bridge EAP traffic, the periodic downtime will eventually self-correct after a few minutes once EAP reauthenticates. However, the problem will persist with each `EAP-Logoff` initiated by the 5268AC, which can happen as often as every 20 minutes.

Possible solutions might include:

**1. Block all EAP traffic after authentication completes**

This should be as simple as doing a `/usr/sbin/ngctl rmhook laneapfilter: eapout` after broadband service is established. However the tricky part is automating when the hook should be disconnected (broadband is up) and when the hook should be reconnected (broadband is down, need to EAP authenticate). Triggers might include:

- Disable hook after `EAP-Success` packet is seen, enable hook after `EAP-Request,Identify`
- Disable after external host is reachable by ping, enable after external host is unreachable
- Disable after X seconds

**2. Drop `EAP-Logoff` packets** 

A more targeted solution might be to just drop any `EAP-Logoff` packets from the 5268AC. I believe this would be possible with additional netgraph nodes. You can provide raw BPF instructions to ng_bpf to filter `EAP-Logoff` events and drop those packets. The PCAP filter is something like `ether proto 0x888e && [15] = 0x02`. This would allow EAP authentication to happen, whenever needed. However, the 5268AC may still initiate `EAP-Start` packets after authentication is complete. I'm not 100% sure, but I imagine this could potentially confuse your authentication state and trigger an `EAP-Failure` / disconnect. 

**3. Unplug 5268AC after authentication completes**

This solution is the easiest, of course. This is effectively replicates the VLAN Swap method that works for many people. Unfortunately without the 5268AC plugged in, this setup won't survive reboots or power outages. If you've lost authentication, you'll need to plugin your 5268AC again.

**4. Trick 5268AC into a good state**

If the 5268AC thinks the broadband service is connected, it shouldn't send erroneous `EAP-Logoff` packets. Getting to this good state might be as easy responding to the DHCP request. But there might be some other subtleties to get to this state. You would also need to consider how to change the broadband state from good to bad when your connection legitimately drops.

At any rate, this is an uphill battle fighting closed-source firmware behavior. I'm personally getting by with solution option 3, but would like to experiment with the other, more resilient options. Open to other ideas...

**Comment by Prodian0013** [comment]
With your experience using option #3, how often have you had to re-establish authentication?  Also, what's the best method for forcing a reauthentication?

**Comment by aus** [comment]
As long as my data link to the ONT is maintained, I have never had to reauthenticate after the first authentication completes. That was for over a month with the 5268AC completely disconnected. I'm not sure that is true for everyone. If the ONT looses its data link, the external gateway will want you to re-authenticate. 

However, I've recently reconnected my 5268AC and have been using a simple ping shell script to toggle the appropriate netgraph configuration. It basically works like this: If an external host is pingable, don't bridge the 5268AC. If an external host is not pingable, bridge the 5268AC in case we need to reauthenticate. It's hacky, but it works. It would probably be better to write a service binary to manage the netgraph.

The shell script seems to work well enough though and allows your connection to recover from reboots or other outages. I'll commit the changes shortly. It still has a few kinks to workout though.

**Comment by BigDogJonx** [comment]
Hi @aus 
Not sure if this just isolated for me, or a bug.  But the file of pfatt.5268AC you put in the /usr/local/etc/rc.d/ directory doesnt actually fire.  According to pfsense manual, it says any script in this directory must end with a .sh (here is the link to their doc, https://docs.netgate.com/pfsense/en/latest/development/executing-commands-at-boot-time.html).  So once I added the .sh to that file, it fired upon reboot, before it never did as my /var/log/pfatt.log never showed anything from pfatt.5268ac.sh.

Question also on the script itself (pfatt-5268AC.sh, file in /root/bin).  Im by no means a script expert or can code much if at all.  But it seems like is this script meant to ping 8.8.8.8 (or host i choose) every 5secs?  Or am I wrong there?  I noticed after I fixed the issue above, it ran once, but hasnt checked again, its been 2hrs.  All I have in the log is the following:

```
2019-02-25 18:16:40 :: [pfatt.sh] :: done!
2019-02-25 18:18:04 :: [pfatt-5268AC.sh] :: Starting 5268AC ping monitor ...
2019-02-25 18:18:04 :: [pfatt-5268AC.sh] :: Connection to 8.8.8.8 is up, but EAP is being bridged!
2019-02-25 18:18:04 :: [pfatt-5268AC.sh] :: Disconnecting netgraph node ... OK!
```

The first line being when it was rebooted (pfsense) after we added the .sh in the rc.d location.  So thats 618p EST, its now 852p and still nothing else.  I assumed this would be constantly monitoring it and I should see messages in this log file.

**Comment by BigDogJonx** [comment]
Actually after adding a bunch of echo statements around the pfatt-5268AC.sh, I think I get what you are doing.  You are basically looping around every 5secs and seems like you are first checking if the ping is successful, then looks like you are checking to see if this EAP is bridged and if it is, you are essentially removing it, and then looks like it just keeps checking that, and if it finds the EAP bridged again (not sure how that would happen), it would disconnect it again.  And then second part with the else, you are basically seeing if the ping fails, then it reconnects it, cause i think your IF ! there means if it does not match, then continue on with bridging the EAP.

**Comment by aus** [comment]
Thanks for pointing that out about the `.sh` suffix. It should be fixed in README now.

And yes, your understanding of the 5268AC workaround is correct. It's a super hacky workaround to check if you have internet access. It just monitors your connectivity and basically toggles on/off the EAP bridge via netgraph.
