### ISSUE TITLE
Step 3 Bug and Thanx!

### ISSUE THREAD

**Issue by flxkid** [aus/pfatt#6]
So under step 3 you show:

```
scp bin/pfatt.sh root@pfsense:/usr/local/etc/rc.d/
ssh root@pfsense chmod +x /root/bin/pfatt.sh

```
You copy into /usr/local/etc/rc.d but then you do the chmod with the file in /root/bin/pfatt.sh

For those that might not be too familiar the process, it could be a bit confusing.

Anyways, I got it working, spun up a VM and built the module on my own, then went through the entire process using a usb ethernet adapter (an Apple one I had laying around to top it off) on my SG-2220 to get rid of the horrible BGW210-700.

It worked perfectly. What a great guide! Next I'm going to attempt ipv6.

**Comment by aus** [comment]
Thanks for pointing this out. Glad to hear you had success!
