### ISSUE TITLE
VLANs and Interfaces

### ISSUE THREAD

**Issue by JaredC01** [aus/pfatt#8]
Not a "bug" per say, but I had an issue I had to troubleshoot tonight when trying this out.  Turns out, my interfaces got changed around, which I was able to re-arrange easy enough, but what I didn't realize, is that my VLANs were still attached to the old interface (which was now the WAN / ONT interface) and it was causing everything but DHCP to work correctly.

It might be worth adding a blurb in the troubleshooting section that if you have VLANs, and the interfaces change, you need to log in, change the VLAN interfaces over to the correct (LAN) interface, and reboot again for the system to work correctly.

Also, thank you very much for all of the hard work on this, I've been looking for a solution for YEARS!

**Comment by aus** [comment]
Thanks! I'm glad this was helpful for you.

Noting what to do with existing VLANs is probably worth pointing out in the instructions. I'll get that added.

It's also worth mentioning (which is in the README as well) that making some changes to the interface settings in pfSense can alter your netgrarph and break pfatt. A reboot usually clears the issue though.

**Comment by JaredC01** [comment]
It's also worth noting that I'm running pfSense in a VM on ESXi.  I believe the issue was with ESXi and the attached interfaces more-so than anything in the script, but a reboot still wouldn't correct the issue, I had to manually change the VLANs over to the 'new' LAN interface.
On 11/4/2018 10:43:58, Austin Robertson <notifications@github.com> wrote:
Closed #8 [https://github.com/aus/pfatt/issues/8] via c9c300e [https://github.com/aus/pfatt/commit/c9c300eea3104764afdb287dad59059c7e0ca98e].

**Comment by aus** [comment]
Interesting. I haven't tried this setup in ESXi yet. I had it working in Proxmox (QEMU) a while back, but moved to physical hardware. In my Proxmox setup, I just passed through all of my pfsense NICs, which worked well. 

If you have any other tips, feel free to submit a PR.
